id: IB88FCFEF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:01:33+00:00'
last_modified: '2022-06-07T22:27:49.677230+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W26461
  title: རྔོག་ལོ་ཙཱ་བའི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7444':
      image_group_id: I00KG03852
      title: ''
      total_pages: 50
      order: 1
      base_file: 7444.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
